### ISSUE TITLE
Add optional token in notice payload

### ISSUE THREAD

**Issue by subzero10** [honeybadger-io/honeybadger-schemas#7]
See [this comment](https://github.com/honeybadger-io/honeybadger-python/pull/140#issuecomment-1485882611).

**Comment by subzero10** [comment]
@joshuap @stympy Do I go ahead and add the property or is there a process that automatically generates the schema?

Additionally, I could port the deployment process to a Github Action 🤔

**Comment by joshuap** [comment]
> @joshuap @stympy Do I go ahead and add the property or is there a process that automatically generates the schema?
> 
> Additionally, I could port the deployment process to a Github Action 🤔

You could submit a PR to add the token. We don't really use the deployment thing currently, so I'd hold off on that. Currently we just manually vendor (i.e. copy it to vendor/) this code in our other apps that need it, since it doesn't update too frequently.
